name: PR Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai requests

    - name: Review PR with ChatGPT
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        OPENAI_MODEL: GPT-4o
        REVIEW_PROMPT: "PRのレビューをお願いします。あなたは優秀なエンジニアで、優しく丁寧なレビューが得意です。"
      run: |
        python .github/scripts/review_pr.py
