name: Auto PR on Push

on:
  create:
    branches:
      - '**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Check cache hit
      run: |
        if [ ${{ steps.cache-pip.outputs.cache-hit }} == 'true' ]; then
          echo "Cache was hit!";
        else
          echo "Cache was missed.";
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Run script to generate PR summary
      id: generate_summary
      run: |
        python .github/scripts/generate_summary.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL: gpt-4o

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Automated PR creation
        branch: auto-pr-branch
        title: Automated Pull Request
        body: ${{ steps.generate_summary.outputs.summary }}
        labels: |
          automated-pr
